---
# Run devsec ansible hardening against host
# https://github.com/dev-sec/ansible-collection-hardening

- hosts: all
  become: true
  collections:
    - devsec.hardening
  roles:
    - role: os_hardening
      vars:
        - os_auth_pw_max_age: 99999
        - os_auth_lockout_time: 300
        - os_pam_enabled: false
      when: os_harden | bool
      tags: devsec_os_hardening_role
    - role: ssh_hardening
      vars:
        - ssh_permit_root_login: 'without-password'
        - sshd_authenticationmethods: 'publickey'
        - sftp_enabled: true
        - network_ipv6_enable: false
      when: ssh_harden | bool
      tags: devsec_ssh_hardening_role
