---
# Run devsec ansible hardening against host
# https://github.com/dev-sec/ansible-collection-hardening

- name: Run Devsec hardening (Debian)
  hosts: all
  become: true
  tasks:
    - name: Include os_hardening
      ansible.builtin.include_role:
        name: devsec.hardening.os_hardening
      vars:
        os_auth_pw_max_age: 99999
        os_auth_lockout_time: 300
        os_pam_enabled: false
      when: os_harden | default(false)
      tags: devsec_hardening_os_hardening

    - name: Include ssh_hardening
      ansible.builtin.include_role:
        name: devsec.hardening.ssh_hardening
      vars:
        ssh_permit_root_login: 'without-password'
        sshd_authenticationmethods: 'publickey'
        sftp_enabled: true
        network_ipv6_enable: false
      when: ssh_harden | default(false)
      tags: devsec_hardening_ssh_hardening
