---
# Base playbook (intended post-hardening)

- name: Nftables configuration
  hosts: all
  become: true
  roles:
    - role: debian_nftables
      when: _nftables_role | bool
      tags: nftables_role
