---
# Update Debian family hosts

- hosts: all
  become: true
  tasks:

  - name: Confirm Debian family
    ansible.builtin.assert:
      that: ansible_facts['os_family'] == "Debian"

  - name: Update all packages
    ansible.builtin.apt:
      name: "*"
      update_cache: true
      state: latest
      autoremove: true

  - name: Check for reboot-required file
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Trigger reboot
    ansible.builtin.debug:
      msg: "Rebooting if required"
    changed_when: reboot_required.stat.exists
    notify: Reboot

  handlers:
  - name: Reboot
    ansible.builtin.reboot:
