---
# Update Debian family hosts
# Restart services/reboot as needed

- name: Update Debian hosts
  hosts: all
  become: true
  tasks:

  - name: Check host Debian
    ansible.builtin.assert:
      that: ansible_facts['os_family'] == "Debian"
      quiet: true

  - name: Update all packages  # noqa package-latest
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true
      autoremove: true

  - name: "Autoremove (kernels for issue #26521)"
    ansible.builtin.command:
      cmd: apt autoremove -y
    changed_when: false

  - name: Install needrestart  # noqa package-latest
    ansible.builtin.apt:
      name: needrestart
      state: latest

  - name: Configure needrestart
    ansible.builtin.copy:
      dest: /etc/needrestart/conf.d/restart.conf
      owner: root
      group: root
      mode: "0644"
      # yamllint disable rule:line-length
      content: |
        # set autorestart default on noninteractive mode
        $nrconf{restart} = exists($ENV{DEBIAN_FRONTEND}) && $ENV{DEBIAN_FRONTEND} eq 'noninteractive' ? 'a' : 'i';
        # drop output to stdout/err
        $nrconf{ui} = 'NeedRestart::UI::stdio';
      # yamllint enable rule:line-length

  - name: Check for reboot-required file
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required
    changed_when: reboot_required.stat.exists
    notify: Reboot

  - name: Restart services as necessary
    # don't bother if rebooting anyway
    when: not reboot_required.stat.exists
    block:
      - name: Run needrestart, reboot for deferred
        ansible.builtin.command:
          cmd: /usr/sbin/needrestart -f noninteractive
        register: needrestart_out
        changed_when: "'deferred:' in needrestart_out.stdout"
        failed_when: needrestart_out.rc != 0
        notify: Reboot

      - name: Display needrestart output
        ansible.builtin.debug:
          msg: "{{ needrestart_out.stdout | split('\n') }}"
        when: update_verbose | default(false)

  - name: Flush handlers
    ansible.builtin.meta: flush_handlers

  handlers:
  - name: Reboot
    ansible.builtin.reboot:
